# Generated by Django 4.2.7 on 2026-02-18 17:31

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(blank=True, help_text="Optionnel. Ne pas utiliser pour l'authentification.", max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='Photo de profil')),
                ('role', models.CharField(choices=[('directeur', '🏢 Directeur'), ('coordinateur', '📊 Coordinateur'), ('responsable_section', '👥 Responsable de Section'), ('membre', '👤 Membre')], default='membre', max_length=20, verbose_name='Rôle système')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('phone_pro', models.CharField(blank=True, max_length=20, verbose_name='Téléphone professionnel')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('date_embauche', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche")),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('notification_desktop', models.BooleanField(default=True, verbose_name='Notifications bureau')),
                ('theme_preference', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='auto', max_length=10, verbose_name='Préférence de thème')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=10, verbose_name='Langue')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('categorie', models.CharField(blank=True, max_length=50, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', colorfield.fields.ColorField(default='#3498db', image_field=None, max_length=18, samples=None, verbose_name='Couleur')),
                ('icon', models.CharField(default='fa-solid fa-building', max_length=50, verbose_name='Icône FontAwesome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, unique=True, verbose_name='Titre du poste')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('categorie', models.CharField(choices=[('direction', 'Direction'), ('management', 'Management'), ('technique', 'Technique'), ('support', 'Support'), ('commercial', 'Commercial'), ('administratif', 'Administratif'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau_hierarchique', models.IntegerField(default=1, help_text='1 = plus bas, 10 = plus haut', verbose_name='Niveau hiérarchique')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Poste actif')),
                ('peut_gerer_equipe', models.BooleanField(default=False, verbose_name='Peut gérer une équipe')),
                ('peut_creer_projets', models.BooleanField(default=False, verbose_name='Peut créer des projets')),
                ('peut_valider_taches', models.BooleanField(default=False, verbose_name='Peut valider des tâches')),
                ('color', colorfield.fields.ColorField(default='#3498db', image_field=None, max_length=18, samples=None, verbose_name='Couleur')),
                ('icon', models.CharField(default='fa-solid fa-briefcase', max_length=50, verbose_name='Icône FontAwesome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['-niveau_hierarchique', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateurs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', colorfield.fields.ColorField(default='#2ecc71', image_field=None, max_length=18, samples=None, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='utilisateurs.department', verbose_name='Département')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['department__name', 'name'],
                'unique_together': {('code', 'department')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='utilisateurs.competence', verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='utilisateurs.department', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='utilisateurs.poste', verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='utilisateurs.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='utilisateur_email_6baed9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='utilisateur_role_de4811_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'section'], name='utilisateur_departm_9c0824_idx'),
        ),
    ]
